# Site settings
title:       Jason Wang
email:       jason.w162@gmail.com
author:      Jason Wang
description: "Thoughts of a software developer"
baseurl:     ""
url:         "https://asur.us"
date_format: "%b %-d, %Y"
avatar: https://avatars1.githubusercontent.com/u/2614464?v=2&s=460

# Google services
google_analytics:
google_verification:

# Optional features
animated:             false
show_related_posts:   false
show_post_footers:    false
show_social_icons:    true
ajaxify_contact_form: false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Facebook Comments plugin
# (leave blank to disable Facebook Comments, otherwise set it to true)
facebook_comments:
facebook_appid:
facebook_comments_number: 10

# Social icons
github_username: jas-on
bitbucket_username:
stackoverflow_id:
twitter_username: jaded_jason
google_plus_id:
linkedin_username:
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: true

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty

gems: [jekyll-paginate]
paginate:     4

sass:
  compressed: true

url: https://asur.us
enforce_ssl: asur.us
